# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dependency_checker.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(702, 694)
        self.widget = QtWidgets.QWidget(Form1)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.buildIoc = QtWidgets.QPushButton(self.widget)
        self.buildIoc.setMaximumSize(QtCore.QSize(32767, 36))
        self.buildIoc.setMinimumSize(QtCore.QSize(0, 38))
        self.buildIoc.setObjectName("buildIoc")
        self.gridLayout.addWidget(self.buildIoc, 2, 1, 1, 1)
        self._2 = QtWidgets.QGridLayout()
        self._2.setSpacing(6)
        self._2.setObjectName("_2")
        self.originalWrite = QtWidgets.QPushButton(self.widget)
        self.originalWrite.setMinimumSize(QtCore.QSize(0, 38))
        self.originalWrite.setObjectName("originalWrite")
        self._2.addWidget(self.originalWrite, 1, 2, 1, 1)
        self.originalPrint = QtWidgets.QPushButton(self.widget)
        self.originalPrint.setMinimumSize(QtCore.QSize(0, 38))
        self.originalPrint.setMaximumSize(QtCore.QSize(32767, 36))
        self.originalPrint.setObjectName("originalPrint")
        self._2.addWidget(self.originalPrint, 1, 0, 1, 1)
        self.originalFrame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.originalFrame.sizePolicy().hasHeightForWidth())
        self.originalFrame.setSizePolicy(sizePolicy)
        self.originalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.originalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.originalFrame.setObjectName("originalFrame")
        self._2.addWidget(self.originalFrame, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self._2.addItem(spacerItem, 1, 1, 1, 1)
        self.gridLayout.addLayout(self._2, 0, 0, 1, 1)
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.consistentWrite = QtWidgets.QPushButton(self.widget)
        self.consistentWrite.setMinimumSize(QtCore.QSize(0, 38))
        self.consistentWrite.setObjectName("consistentWrite")
        self.gridlayout.addWidget(self.consistentWrite, 1, 2, 1, 1)
        self.consistentPrint = QtWidgets.QPushButton(self.widget)
        self.consistentPrint.setMinimumSize(QtCore.QSize(0, 38))
        self.consistentPrint.setMaximumSize(QtCore.QSize(32767, 36))
        self.consistentPrint.setObjectName("consistentPrint")
        self.gridlayout.addWidget(self.consistentPrint, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.consistentFrame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consistentFrame.sizePolicy().hasHeightForWidth())
        self.consistentFrame.setSizePolicy(sizePolicy)
        self.consistentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.consistentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.consistentFrame.setObjectName("consistentFrame")
        self.gridlayout.addWidget(self.consistentFrame, 0, 0, 1, 3)
        self.gridLayout.addLayout(self.gridlayout, 0, 1, 1, 1)
        self.gridlayout1 = QtWidgets.QGridLayout()
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.latestWrite = QtWidgets.QPushButton(self.widget)
        self.latestWrite.setMinimumSize(QtCore.QSize(0, 38))
        self.latestWrite.setObjectName("latestWrite")
        self.gridlayout1.addWidget(self.latestWrite, 1, 2, 1, 1)
        self.latestPrint = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.latestPrint.sizePolicy().hasHeightForWidth())
        self.latestPrint.setSizePolicy(sizePolicy)
        self.latestPrint.setMinimumSize(QtCore.QSize(0, 38))
        self.latestPrint.setObjectName("latestPrint")
        self.gridlayout1.addWidget(self.latestPrint, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(62, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2, 1, 1, 1, 1)
        self.latestFrame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.latestFrame.sizePolicy().hasHeightForWidth())
        self.latestFrame.setSizePolicy(sizePolicy)
        self.latestFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.latestFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.latestFrame.setObjectName("latestFrame")
        self.gridlayout1.addWidget(self.latestFrame, 0, 0, 1, 3)
        self.gridLayout.addLayout(self.gridlayout1, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textLabel1 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel1.sizePolicy().hasHeightForWidth())
        self.textLabel1.setSizePolicy(sizePolicy)
        self.textLabel1.setMinimumSize(QtCore.QSize(5, 16))
        self.textLabel1.setMaximumSize(QtCore.QSize(32767, 16))
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.horizontalLayout.addWidget(self.textLabel1)
        self.textLabel1_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textLabel1_2.sizePolicy().hasHeightForWidth())
        self.textLabel1_2.setSizePolicy(sizePolicy)
        self.textLabel1_2.setMinimumSize(QtCore.QSize(5, 16))
        self.textLabel1_2.setStyleSheet("QLabel {background-color: rgb(203,255,197) }")
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.horizontalLayout.addWidget(self.textLabel1_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        Form1.setCentralWidget(self.widget)

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)

    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Form1"))
        self.buildIoc.setText(_translate("Form1", "Build Test IOC"))
        self.originalWrite.setText(_translate("Form1", "Write Changes"))
        self.originalPrint.setText(_translate("Form1", "Print Changes"))
        self.consistentWrite.setText(_translate("Form1", "Write Changes"))
        self.consistentPrint.setText(_translate("Form1", "Print Changes"))
        self.latestWrite.setText(_translate("Form1", "Write Changes"))
        self.latestPrint.setText(_translate("Form1", "Print Changes"))
        self.textLabel1.setText(_translate("Form1", "<html><head/><body><p>Key: <span style=\" color:#999600;\">In Clash</span>, <span style=\" color:#ff0000;\">Causing Clash</span>, <span style=\" color:#a020f0;\">Invalid</span>, </p></body></html>"))
        self.textLabel1_2.setText(_translate("Form1", "Update Available"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form1 = QtWidgets.QMainWindow()
    ui = Ui_Form1()
    ui.setupUi(Form1)
    Form1.show()
    sys.exit(app.exec_())
